version: '3.4'

services:
  summer-chill:
    image: summer-chill
    environment:
      - FGLair__Username=your-email@example.com
      - FGLair__Password=your-password
      - FGLair__DeviceDsn=device-dsn