@device-dsn = "YOUR_DEVICE_DSN_HERE"
@access-token = "SET VALUE AFTER AUTHENTICATION"

### Authenticate against FGLair API
POST https://user-field.aylanetworks.com/users/sign_in.json
Content-Type: application/json
Accept: application/json
User-Agent: FGLAir/2.0
Connection: keep-alive
Accept-Encoding: gzip, deflate, br

{
  "user": {
    "email": "---",
    "password": "---",
    "application": {
      "app_id": "CJIOSP-id",
      "app_secret": "CJIOSP-Vb8MQL_lFiYQ7DKjN0eCFXznKZE"
    }
  }
}

### Response
@access_token = "45da2ebe41544dee9161052aac407394"

### Get Device Properties (including louver position)
# After running the authentication request above:
# 1. Copy the "access_token" value from the response
# 2. Replace YOUR_ACCESS_TOKEN_HERE below with that value
# 3. Then execute this request
GET https://user-field.aylanetworks.com/apiv1/dsns/{{device-dsn}}/properties
Accept: application/json
User-Agent: FGLAir/2.0
Authorization: auth_token {{access_token}}
Connection: keep-alive
Accept-Encoding: gzip, deflate, br

###

### set device property af_vertical_num_dir to 8

POST https://user-field.aylanetworks.com/apiv1/dsns/{{device-dsn}}/properties/af_vertical_direction/datapoints
Content-Type: application/json
Accept: application/json
User-Agent: FGLAir/2.0
Authorization: auth_token {{access_token}}
Connection: keep-alive
Accept-Encoding: gzip, deflate, br

{
  "datapoint": {
    "value": "8"
  }
}

### device response

# HTTP/1.1 200 OK
# date: Thu, 26 Jun 2025 14:55:55 GMT
# content-type: application/json;charset=utf-8
# content-security-policy: frame-ancestors 'none'
# etag: W/"a275ba999ef5875071bd7e46c09bf307"
# last-modified: Wed, 14 Dec 2050 18:43:58 GMT
# referrer-policy: strict-origin-when-cross-origin
# status: 200 OK
# strict-transport-security: max-age=63072000; includeSubDomains; preload
# vary: Origin
# x-content-type-options: nosniff
# x-download-options: noopen
# x-frame-options: DENY
# x-permitted-cross-domain-policies: none
# x-request-id: a9212470-529d-11f0-8525-b1e8899aa477
# x-runtime: 0.109741
# x-xss-protection: 1; mode=block
# access-control-allow-origin: *
# access-control-allow-credentials: true
# access-control-allow-methods: GET,PUT,POST,DELETE,PATCH,OPTIONS
# access-control-allow-headers: accept,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,x-csrf-token,Content-Disposition,X-Pingother
# access-control-max-age: 1728000
# via: 1.1 google
# transfer-encoding: chunked

# [
#   {
#     "property": {
#       "type": "Property",
#       "name": "adjust_temperature",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:59Z",
#       "key": 153969125,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "adjust_temperature",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 210,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_horizontal_direction",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:59Z",
#       "key": 153969127,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_horizontal_direction",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 4,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_horizontal_num_dir",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:59Z",
#       "key": 153969122,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_horizontal_num_dir",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 5,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_horizontal_swing",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:59Z",
#       "key": 153969179,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_horizontal_swing",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_vertical_direction",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:00Z",
#       "key": 153969126,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_vertical_direction",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 7,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_vertical_num_dir",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:00Z",
#       "key": 153969121,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_vertical_num_dir",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 8,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "af_vertical_swing",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:00Z",
#       "key": 153969178,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "af_vertical_swing",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "auto_off_time",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:00Z",
#       "key": 153969170,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "auto_off_time",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "auto_on_off_set_time",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:01Z",
#       "key": 153969167,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "auto_on_off_set_time",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "auto_on_off_time",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:01Z",
#       "key": 153969172,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "auto_on_off_time",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "auto_save_set_time",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:01Z",
#       "key": 153969166,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "auto_save_set_time",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 2,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "auto_save_time",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:01Z",
#       "key": 153969168,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "auto_save_time",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 20,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "building_name",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:20Z",
#       "key": 153969180,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "building_name",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": "NoGroup",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "child_lock_mode",
#       "base_type": "boolean",
#       "read_only": true,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:01Z",
#       "key": 153969143,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "child_lock_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "child_lock_pin",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:20Z",
#       "key": 153969163,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "child_lock_pin",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": "0",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "coil_dry_mode",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:02Z",
#       "key": 153969133,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "coil_dry_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "comm_version",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:02Z",
#       "key": 153969176,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "comm_version",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "demand_control",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:02Z",
#       "key": 153969177,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "demand_control",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "device_capabilities",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:02Z",
#       "key": 153969120,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "device_capabilities",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 229375,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "device_name",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:20Z",
#       "key": 153969141,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "device_name",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": "AC",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "display_temperature",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:03Z",
#       "key": 153969184,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "display_temperature",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 7250,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "economy_mode",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:03Z",
#       "key": 153969134,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "economy_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "error_code",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:03Z",
#       "key": 153969135,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "error_code",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "fan_speed",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:03Z",
#       "key": 153969124,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "fan_speed",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 1,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "filter_sign_reset_display",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:07Z",
#       "key": 163126433,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "filter_sign_reset_display",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "get_prop",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:03Z",
#       "key": 153969183,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "get_prop",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "human_det",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:04Z",
#       "key": 153969162,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "human_det",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 1,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "human_det_auto_off",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:04Z",
#       "key": 153969169,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "human_det_auto_off",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "human_det_auto_on_off",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:04Z",
#       "key": 153969171,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "human_det_auto_on_off",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "human_det_auto_save",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:04Z",
#       "key": 153969130,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "human_det_auto_save",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 1,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "indoor_fan_control",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:04Z",
#       "key": 153969129,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "indoor_fan_control",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "master_timer_on_off_1",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:58Z",
#       "key": 153969181,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "master_timer_on_off_1",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "master_timer_on_off_2",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:59Z",
#       "key": 153969182,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "master_timer_on_off_2",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "mcu_error",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:05Z",
#       "key": 153969185,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "mcu_error",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 12,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "mcu_fw_version",
#       "base_type": "string",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:06:58Z",
#       "key": 153969165,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": true,
#       "display_name": "mcu_fw_version",
#       "host_sw_version": true,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": "LF 1800.05.02",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "min_heat",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:05Z",
#       "key": 153969131,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "min_heat",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "model_name",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:22Z",
#       "key": 153969186,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "model_name",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": "E_2025-06-26",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "operation_mode",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:05Z",
#       "key": 153969123,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "operation_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 3,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "op_status",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:05Z",
#       "key": 153969136,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "op_status",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "outdoor_low_noise",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:06Z",
#       "key": 153969128,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "outdoor_low_noise",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "outdoor_temperature",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "null",
#       "key": 153969173,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "outdoor_temperature",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": null,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "powerful_mode",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:06Z",
#       "key": 153969132,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "powerful_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "rc_prohibition",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:06Z",
#       "key": 153969164,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "rc_prohibition",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "reboot_range",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "null",
#       "key": 204183757,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "reboot_range",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": null,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "reboot_start",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "null",
#       "key": 204183756,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "reboot_start",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": null,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "refresh",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2022-08-13T17:01:23Z",
#       "key": 153969161,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "refresh",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_contact_email",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:22Z",
#       "key": 153969146,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_contact_email",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": " ",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_contact_name",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:22Z",
#       "key": 153969144,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_contact_name",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": " ",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_contact_phone",
#       "base_type": "string",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:23Z",
#       "key": 153969145,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_contact_phone",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": " ",
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_function_address",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:06Z",
#       "key": 153969140,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_function_address",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_function_number",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:52Z",
#       "key": 153969138,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_function_number",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_function_setting",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:53Z",
#       "key": 153969139,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_function_setting",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "service_mode",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:53Z",
#       "key": 153969174,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "service_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "system_type",
#       "base_type": "integer",
#       "read_only": true,
#       "direction": "output",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:06Z",
#       "key": 153969175,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "system_type",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "test_run",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:07Z",
#       "key": 153969137,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "test_run",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "wifi_led_enable",
#       "base_type": "boolean",
#       "read_only": true,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2025-06-26T09:07:07Z",
#       "key": 153969142,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "wifi_led_enable",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": "AYLA::device",
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_1_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:55Z",
#       "key": 153969153,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_1_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_2_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:55Z",
#       "key": 153969154,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_2_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_3_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:56Z",
#       "key": 153969155,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_3_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_4_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:56Z",
#       "key": 153969156,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_4_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_5_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:56Z",
#       "key": 153969157,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_5_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_6_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:57Z",
#       "key": 153969158,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_6_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_7_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:57Z",
#       "key": 153969159,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_7_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_8_num_outlets",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:58Z",
#       "key": 153969160,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_8_num_outlets",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_function_setting",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:58Z",
#       "key": 153969151,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_function_setting",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_setting",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:58Z",
#       "key": 153969152,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_setting",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_temp_sensor_mode",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:59Z",
#       "key": 153969149,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_temp_sensor_mode",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_temp_sensor_select",
#       "base_type": "integer",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:31:59Z",
#       "key": 153969150,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_temp_sensor_select",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_use_opt_sensor_1",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:32:00Z",
#       "key": 153969147,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_use_opt_sensor_1",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   },
#   {
#     "property": {
#       "type": "Property",
#       "name": "zone_use_opt_sensor_2",
#       "base_type": "boolean",
#       "read_only": false,
#       "direction": "input",
#       "scope": "user",
#       "data_updated_at": "2020-04-28T03:32:00Z",
#       "key": 153969148,
#       "device_key": 25589941,
#       "product_name": "AC000W002826905",
#       "track_only_changes": false,
#       "display_name": "zone_use_opt_sensor_2",
#       "host_sw_version": false,
#       "time_series": false,
#       "derived": false,
#       "app_type": null,
#       "recipe": null,
#       "value": 0,
#       "generated_from": null,
#       "generated_at": null,
#       "denied_roles": [],
#       "ack_enabled": false,
#       "retention_days": 30,
#       "ack_status": null,
#       "ack_message": null,
#       "acked_at": null
#     }
#   }
# ]
