name: github-actions-summer-chill

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
    branches: [ main ]  # Ensure tags are on main branch

env:
  IMAGE_NAME: summer-chill
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Verify tag is on main branch
      run: |
        # Check if the tag points to a commit that exists on main branch
        TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
        if ! git merge-base --is-ancestor $TAG_COMMIT origin/main; then
          echo "Error: Tag ${{ github.ref }} is not on the main branch"
          exit 1
        fi
        echo "Tag ${{ github.ref }} is on main branch ✓"
    
    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - name: Azure Login with OIDC
      uses: Azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Build .NET application
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
    
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}
    
    - name: Build and push Docker image
      run: |
        # Get the ACR login server
        ACR_LOGIN_SERVER=$(az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "loginServer" --output tsv)
        
        # Build the Docker image with tag version
        docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }} .
        docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest .
        
        # Push the Docker image
        docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
        docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest
    
    - name: Output deployment information
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --query "loginServer" --output tsv)
        echo "Container Registry: $ACR_LOGIN_SERVER"
        echo "Tagged Image: $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}"
        echo "Latest Image: $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest"
        echo "Git Tag: ${{ steps.extract_tag.outputs.tag }}"
